// End User Overview - FlutterGristAPI
// Role description, what end users can do, basic concepts

#import "../common/styles.typ": *

= End User Role Overview

This documentation is designed for people who use the Flutter applications generated by FlutterGristAPI. You don't need any technical knowledge or programming experience - this guide will help you navigate and use the app effectively.

== Who Are End Users?

As an end user, you are someone who:

- Uses the mobile or desktop application to view and manage business data
- Logs in with an email and password to access your organization's information
- Views records, searches for data, and navigates between different sections
- Does not need to know how the app was built or how it connects to the database
- Simply needs to get your work done efficiently using the app

#info_box(type: "info")[
  **Not a Technical Person?**

  Perfect! This guide is written specifically for non-technical users. You don't need to understand databases, programming, or technical jargon - just follow the simple steps to use your app effectively.
]

== What Can You Do?

The FlutterGristAPI application gives you the ability to:

=== 1. View Your Data

- Browse through lists of records (products, customers, orders, etc.)
- See information organized in easy-to-read tables
- View detailed information about individual records
- Navigate between related information

=== 2. Search and Filter

- Quickly find what you're looking for using the search bar
- Filter data to show only what matters to you
- Sort information by different columns (name, date, etc.)
- Navigate through pages of results

=== 3. Access from Anywhere

- Use the app on your smartphone or tablet
- Access the same data from your desktop computer
- Your data stays synchronized across all devices
- Works on both iOS (iPhone/iPad) and Android devices

=== 4. Stay Secure

- Your login credentials keep your data private
- Each user sees only what they're authorized to access
- Automatic logout after inactivity keeps your account secure
- Role-based permissions control what you can view

== Key Concepts

=== Applications and Data

The app you're using displays information stored in your organization's database. Think of it like a digital filing cabinet:

- *Tables*: Different types of information (like file folders)
- *Records*: Individual items in each table (like documents in a folder)
- *Fields*: Specific pieces of information about each item (like lines on a form)

=== Navigation

The app uses simple navigation patterns you're already familiar with:

- *Drawer Menu*: A sliding panel on the left with all available sections
- *Master Pages*: Lists of items you can browse and search
- *Detail Pages*: Detailed view of a single item when you tap/click it
- *Back Button*: Returns you to the previous screen

=== Your User Role

Every user has a *role* that determines what they can see and do:

#table(
  columns: (auto, 1fr),
  align: (left, left),
  [*Role*], [*What You Can Do*],

  [User], [View standard data, search and browse records],
  [Manager], [View all data, access additional reports and information],
  [Admin], [View everything including system information and user management],
)

Your administrator assigns your role when your account is created.

=== Read-Only Access (Version 0.1.0)

#info_box(type: "warning")[
  **Current Version: Read-Only**

  The current version of FlutterGristAPI (0.1.0) provides *read-only* access to data. This means you can:

  - View all information
  - Search and filter data
  - Navigate between records

  You *cannot* currently:

  - Edit existing records
  - Create new records
  - Delete information

  These features are planned for future versions.
]

== Basic Workflow

A typical session with the app follows this pattern:

=== 1. Login

- Open the app
- Enter your email address
- Enter your password
- Tap the "Login" button

=== 2. Navigate

- Open the drawer menu (tap the menu icon ☰)
- Choose the section you want to view
- Browse the list of available items

=== 3. Search

- Use the search bar at the top
- Type what you're looking for
- Results filter automatically as you type

=== 4. View Details

- Tap/click any item in a list
- View complete information about that item
- Use the back button to return to the list

=== 5. Logout

- Open the drawer menu
- Tap your profile name at the top
- Choose "Logout" to end your session

== Understanding the Interface

=== Main Screen Elements

```
┌─────────────────────────────────────┐
│ ☰  Page Title              🔍       │ ← Top Bar
├─────────────────────────────────────┤
│                                     │
│   ┌─────────────────────────────┐  │
│   │  List of Items              │  │ ← Content Area
│   │  • Item 1                   │  │
│   │  • Item 2                   │  │
│   │  • Item 3                   │  │
│   └─────────────────────────────┘  │
│                                     │
│         [< Previous] [Next >]       │ ← Pagination
└─────────────────────────────────────┘
```

*Key Elements:*

- *Menu Icon (☰)*: Opens the drawer menu
- *Search Icon (🔍)*: Opens the search bar
- *Content Area*: Shows your data (tables, forms, or static pages)
- *Pagination Controls*: Move between pages of results

=== Drawer Menu

```
┌─────────────────────────────┐
│  👤 Your Name              │ ← User Profile
│     your.email@company.com │
│     Role: Manager          │
├─────────────────────────────┤
│  🏠 Home                   │ ← Navigation
│  📦 Products               │   Menu Items
│  👥 Customers              │
│  📊 Reports                │
│  ⚙️  Settings              │
├─────────────────────────────┤
│  🚪 Logout                 │ ← Logout Button
└─────────────────────────────┘
```

=== Data Table View

When viewing lists of information:

#table(
  columns: (auto, auto, auto, auto),
  align: (left, left, left, left),
  [*#*], [*Name*], [*Category*], [*Status*],
  [1], [Product A], [Electronics], [Active],
  [2], [Product B], [Furniture], [Active],
  [3], [Product C], [Electronics], [Inactive],
)

- *# Column*: Sequential record number (makes it easy to reference items)
- *Data Columns*: Information about each record
- *Sortable*: Click/tap column headers to sort
- *Clickable Rows*: Tap any row to see full details

=== Detail View

When viewing a single record:

```
┌─────────────────────────────────────┐
│ ← Back        Product Details       │
├─────────────────────────────────────┤
│                                     │
│  Name:      Product A               │
│  Category:  Electronics             │
│  Price:     $99.99                  │
│  Status:    Active                  │
│  Description:                       │
│  A high-quality electronic device   │
│  perfect for everyday use.          │
│                                     │
└─────────────────────────────────────┘
```

- All information displayed in a readable form
- Clear labels for each field
- Back button returns to the list

== Data Organization

=== Record Numbers

Each record has two numbers:

- *Record Number*: A sequential number (1, 2, 3...) that's easy to remember and reference
- *Internal ID*: A technical identifier used by the system (you usually don't see this)

The record number makes it easy to say "Check record number 42" when discussing data with colleagues.

=== Sorting

Click or tap column headers to sort data:

- First click: Sort ascending (A to Z, 0 to 9, oldest to newest)
- Second click: Sort descending (Z to A, 9 to 0, newest to oldest)
- Third click: Return to original order

=== Searching

The search feature looks through all visible columns:

- Type in the search bar
- Results filter in real-time
- Search is case-insensitive (finds "apple" whether you type "Apple" or "APPLE")
- Clear the search box to see all results again

== Getting Started

Now that you understand the basics, continue to the *Quickstart Guide* to:

1. Log in for the first time
2. Navigate the interface
3. Search for data
4. View record details
5. Use all the basic features

#section_separator()

#info_box(type: "success")[
  **Ready to Start?**

  Continue to *quickstart.typ* for a step-by-step guide to using the app for the first time, or jump to *reference.typ* for a complete feature reference.
]
