# =============================================================================
# Concourse CI/CD Pipeline for Flutter Grist Widgets
# =============================================================================
#
# This pipeline automates:
# 1. Code quality checks (Flutter analyze)
# 2. Unit tests (77 tests)
# 3. Deployment to Raspberry Pi (manual trigger)
#
# Pipeline flow:
#   git push → quality-checks (analyze + test) → build → deploy-production
#
# Usage:
#   fly -t local set-pipeline -p flutter-grist -c pipeline.yml -l credentials.yml
#   fly -t local unpause-pipeline -p flutter-grist
#
# =============================================================================

# -----------------------------------------------------------------------------
# RESOURCES
# -----------------------------------------------------------------------------
# Resources represent external inputs/outputs that pipelines interact with

resources:
  # Source code from Git
  - name: source-code
    type: git
    icon: github
    source:
      uri: https://github.com/PierreBx/flutterGristAPI.git
      branch: main
      # For private repos, add:
      # private_key: ((github-private-key))
    check_every: 1m  # Check for new commits every minute

  # Flutter Docker image (for running tests/analysis)
  - name: flutter-image
    type: registry-image
    icon: docker
    source:
      repository: instrumentisto/flutter
      tag: latest

# -----------------------------------------------------------------------------
# JOBS
# -----------------------------------------------------------------------------

jobs:
  # ---------------------------------------------------------------------------
  # Job 1: Quality Checks (Analysis + Tests)
  # ---------------------------------------------------------------------------
  - name: quality-checks
    public: true
    plan:
      - get: source-code
        trigger: true  # Auto-run when new commits detected

      - get: flutter-image

      # Task 1: Flutter Analyze
      - task: flutter-analyze
        image: flutter-image
        config:
          platform: linux
          inputs:
            - name: source-code
          caches:
            - path: source-code/flutter-module/.dart_tool
            - path: /root/.pub-cache
          run:
            path: /bin/sh
            args:
              - -ec
              - |
                echo "=========================================="
                echo "🔍 Running Flutter Analysis..."
                echo "=========================================="
                cd source-code/flutter-module

                # Get dependencies
                flutter pub get

                # Run analysis
                flutter analyze --no-fatal-infos --no-fatal-warnings

                EXIT_CODE=$?
                if [ $EXIT_CODE -eq 0 ]; then
                  echo "✅ Analysis passed - no issues found"
                else
                  echo "❌ Analysis failed - please fix the issues above"
                  exit $EXIT_CODE
                fi

      # Task 2: Flutter Test
      - task: flutter-test
        image: flutter-image
        config:
          platform: linux
          inputs:
            - name: source-code
          caches:
            - path: source-code/flutter-module/.dart_tool
            - path: /root/.pub-cache
          run:
            path: /bin/sh
            args:
              - -ec
              - |
                echo "=========================================="
                echo "🧪 Running Flutter Tests (77 tests)..."
                echo "=========================================="
                cd source-code/flutter-module

                # Get dependencies
                flutter pub get

                # Run tests with expanded output
                flutter test --reporter expanded --no-pub

                EXIT_CODE=$?
                if [ $EXIT_CODE -eq 0 ]; then
                  echo "✅ All tests passed!"
                else
                  echo "❌ Some tests failed - please fix them"
                  exit $EXIT_CODE
                fi

      # Task 3: Test Coverage Report
      - task: test-coverage
        image: flutter-image
        config:
          platform: linux
          inputs:
            - name: source-code
          outputs:
            - name: coverage-report
          caches:
            - path: source-code/flutter-module/.dart_tool
            - path: /root/.pub-cache
          run:
            path: /bin/sh
            args:
              - -ec
              - |
                echo "=========================================="
                echo "📊 Generating Test Coverage Report..."
                echo "=========================================="
                cd source-code/flutter-module

                # Install lcov for coverage reporting
                apk add --no-cache lcov perl

                # Get dependencies (if not cached)
                flutter pub get

                # Run tests with coverage
                flutter test --coverage --no-pub

                # Generate HTML report
                echo ""
                echo "Generating HTML coverage report..."
                genhtml coverage/lcov.info -o coverage/html --quiet

                # Display coverage summary
                echo ""
                echo "=========================================="
                echo "📈 Coverage Summary:"
                echo "=========================================="
                lcov --summary coverage/lcov.info

                # Extract coverage percentage
                COVERAGE=$(lcov --summary coverage/lcov.info 2>&1 | grep "lines" | grep -oP '\d+\.\d+(?=%)')
                echo ""
                echo "Total Line Coverage: ${COVERAGE}%"

                # Set minimum coverage threshold
                MIN_COVERAGE=60.0

                # Compare coverage (using awk for float comparison)
                if awk "BEGIN {exit !($COVERAGE >= $MIN_COVERAGE)}"; then
                  echo "✅ Coverage meets minimum threshold (${MIN_COVERAGE}%)"
                else
                  echo "⚠️  Warning: Coverage ${COVERAGE}% is below threshold ${MIN_COVERAGE}%"
                  echo "This is a warning only - pipeline will continue"
                  echo "Consider adding more tests to improve coverage"
                fi

                # Copy coverage report to output
                cp -r coverage ../coverage-report/

                echo ""
                echo "Coverage report generated at: coverage/html/index.html"
                echo "✅ Coverage analysis complete!"

      # Task 4: Secrets Scanning
      - task: secrets-scan
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: alpine
              tag: latest
          inputs:
            - name: source-code
          run:
            path: /bin/sh
            args:
              - -ec
              - |
                echo "=========================================="
                echo "🔐 Scanning for Secrets and Credentials..."
                echo "=========================================="

                # Install required tools
                apk add --no-cache wget tar gzip git

                # Download gitleaks
                echo "Downloading gitleaks..."
                wget -q https://github.com/gitleaks/gitleaks/releases/download/v8.18.4/gitleaks_8.18.4_linux_x64.tar.gz
                tar -xzf gitleaks_8.18.4_linux_x64.tar.gz
                chmod +x gitleaks

                cd source-code

                # Initialize git if needed (for gitleaks to work)
                if [ ! -d .git ]; then
                  git init
                  git add .
                  git config user.email "ci@concourse.local"
                  git config user.name "Concourse CI"
                  git commit -m "Temporary commit for scanning"
                fi

                echo ""
                echo "Running secrets detection..."

                # Run gitleaks
                if ../gitleaks detect --source . --verbose --no-git --report-format json --report-path gitleaks-report.json; then
                  echo ""
                  echo "✅ No secrets detected in codebase"
                else
                  EXIT_CODE=$?
                  echo ""
                  echo "=========================================="
                  echo "⚠️  POTENTIAL SECRETS DETECTED!"
                  echo "=========================================="

                  # Show findings
                  if [ -f gitleaks-report.json ]; then
                    cat gitleaks-report.json
                  fi

                  echo ""
                  echo "Please review the findings above and remove any sensitive data."
                  echo "Common issues:"
                  echo "  - API keys in code"
                  echo "  - Passwords or tokens"
                  echo "  - Private keys"
                  echo "  - Database connection strings with credentials"
                  echo ""
                  echo "If these are false positives, add them to .gitleaksignore"
                  echo "=========================================="

                  exit $EXIT_CODE
                fi

    on_success:
      task: notify-success
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: alpine
            tag: latest
        run:
          path: /bin/sh
          args:
            - -c
            - |
              echo "✅ Quality checks passed successfully!"
              echo "All tests and analysis completed without issues."

    on_failure:
      task: notify-failure
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: alpine
            tag: latest
        run:
          path: /bin/sh
          args:
            - -c
            - |
              echo "❌ Quality checks failed!"
              echo "Please review the errors above and fix them."
              echo "Pipeline will not proceed to deployment."

  # ---------------------------------------------------------------------------
  # Job 2: Build (Optional - for web build)
  # ---------------------------------------------------------------------------
  - name: build
    public: true
    plan:
      - get: source-code
        passed: [quality-checks]  # Only run if quality-checks passed
        trigger: false  # Manual trigger only

      - get: flutter-image

      - task: build-flutter-web
        image: flutter-image
        config:
          platform: linux
          inputs:
            - name: source-code
          outputs:
            - name: build-output
          caches:
            - path: source-code/flutter-module/.dart_tool
            - path: /root/.pub-cache
          run:
            path: /bin/sh
            args:
              - -ec
              - |
                echo "=========================================="
                echo "🔨 Building Flutter Web App..."
                echo "=========================================="
                cd source-code/flutter-module

                flutter pub get
                flutter build web --release

                # Copy build output
                cp -r build/web/* ../build-output/

                echo "✅ Build completed successfully!"
                ls -lah ../build-output/

  # ---------------------------------------------------------------------------
  # Job 3: Deploy to Raspberry Pi (Manual trigger)
  # ---------------------------------------------------------------------------
  - name: deploy-production
    public: true
    plan:
      - get: source-code
        passed: [quality-checks]  # Must pass quality checks first
        trigger: false  # Manual deployment only

      - task: ansible-deploy
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: alpine
              tag: latest
          inputs:
            - name: source-code
          params:
            RASPBERRY_PI_HOST: ((raspberry-pi-host))
            RASPBERRY_PI_USER: ((raspberry-pi-user))
            SSH_PRIVATE_KEY: ((ssh-private-key))
          run:
            path: /bin/sh
            args:
              - -ec
              - |
                echo "=========================================="
                echo "🚀 Deploying to Raspberry Pi..."
                echo "=========================================="
                echo "Target: $RASPBERRY_PI_USER@$RASPBERRY_PI_HOST"

                # Install required packages
                apk add --no-cache openssh ansible

                # Setup SSH
                mkdir -p ~/.ssh
                echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
                ssh-keyscan -H $RASPBERRY_PI_HOST >> ~/.ssh/known_hosts 2>/dev/null

                # Test SSH connection
                ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $RASPBERRY_PI_USER@$RASPBERRY_PI_HOST "echo '✅ SSH connection successful'"

                # Run Ansible deployment
                cd source-code/deployment-module
                ansible-playbook playbooks/configure_server.yml \
                  -i inventory/hosts.yml \
                  --tags app \
                  -v

                echo "✅ Deployment completed!"

      - task: health-check
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: alpine
              tag: latest
          params:
            RASPBERRY_PI_HOST: ((raspberry-pi-host))
            RASPBERRY_PI_USER: ((raspberry-pi-user))
            SSH_PRIVATE_KEY: ((ssh-private-key))
          run:
            path: /bin/sh
            args:
              - -ec
              - |
                echo "=========================================="
                echo "🔍 Running Health Checks..."
                echo "=========================================="

                # Install required packages
                apk add --no-cache openssh curl

                # Setup SSH
                mkdir -p ~/.ssh
                echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa

                # Run remote health check script
                echo "Running health check script on Raspberry Pi..."
                ssh -i ~/.ssh/id_rsa $RASPBERRY_PI_USER@$RASPBERRY_PI_HOST \
                  '/opt/monitoring/health_check.sh' || true

                # Check HTTP endpoint
                echo ""
                echo "Checking HTTP health endpoint..."
                HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://$RASPBERRY_PI_HOST/health || echo "000")

                if [ "$HTTP_STATUS" = "200" ]; then
                  echo "✅ Health check passed (HTTP $HTTP_STATUS)"
                elif [ "$HTTP_STATUS" = "000" ]; then
                  echo "⚠️  Warning: Could not reach health endpoint (service may still be starting)"
                  exit 0  # Don't fail the pipeline
                else
                  echo "❌ Health check failed (HTTP $HTTP_STATUS)"
                  exit 1
                fi

    on_success:
      task: notify-deployment-success
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: alpine
            tag: latest
        params:
          RASPBERRY_PI_HOST: ((raspberry-pi-host))
        run:
          path: /bin/sh
          args:
            - -c
            - |
              echo "=========================================="
              echo "✅ DEPLOYMENT SUCCESSFUL!"
              echo "=========================================="
              echo "Application deployed to: $RASPBERRY_PI_HOST"
              echo "Health checks passed"
              echo "=========================================="

    on_failure:
      task: notify-deployment-failure
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: alpine
            tag: latest
        run:
          path: /bin/sh
          args:
            - -c
            - |
              echo "=========================================="
              echo "❌ DEPLOYMENT FAILED!"
              echo "=========================================="
              echo "Please check the logs above for details"
              echo "You may need to manually investigate the Raspberry Pi"
              echo "=========================================="

# -----------------------------------------------------------------------------
# GROUPS (for organizing jobs in the UI)
# -----------------------------------------------------------------------------
groups:
  - name: all
    jobs:
      - quality-checks
      - build
      - deploy-production

  - name: ci
    jobs:
      - quality-checks

  - name: deployment
    jobs:
      - build
      - deploy-production
